CREATE TABLE IF NOT EXISTS EMPLOYEE(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR NOT NULL,
    CHAT_ID VARCHAR,
	IS_ADMIN BOOLEAN
);

CREATE TABLE IF NOT EXISTS WORK(
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL,
    WORK_DATE DATE,
    START_DATE DATE,
    END_DATE DATE,

    CONSTRAINT FK_WORK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

DELETE FROM EMPLOYEE WHERE ID=1 OR ID=4; 
DROP TABLE EMPLOYEE;
DROP TABLE WORK;

UPDATE EMPLOYEE
SET IS_ADMIN = true 
WHERE ID = 1;

SELECT * FROM EMPLOYEE;